### PR TITLE
Feature/login page

### PR DESCRIPTION
**Pull request by joonhoswe**

### CODE REVIEW

**Comment by joonhoswe** [comment]
the log in page is ready, the buttons just need to be connected to clerk now.

**Comment by AustinWheel** [comment]
To pull and apply the most recent changes, 

- do a `git pull` 
- then from your `backend` directory,  do `pip install -r requirements.txt`
- then you can do `python manage.py migrate`
- then `python manage.py shell < scripts/upload_featured.py`
- After that you should be good to go and can start your server

Comments:
I couldn't repoduce the issue that Yonathan was getting with the featured script not uploading properly, maybe try again.
I was able to delete the featured from my database and rerun the script which create new ones, so maaybe try rerunning it.

If any of you guys run into issues just reach to me and I can try to hop in and help.

**Comment by joonhoswe** [comment]
register site is fully functional and is showing new account creations in Clerk dashboard. 

**issue 1:**
not sure why login page won't link with register, but working on it atm. 

**issue 2:**
images won't work for login site, commented out for now.

**Comment by joonhoswe** [comment]
ready for merging from my side

**Pull request merged**
